name: Generate css vars from tokens and copy
on: [push]

jobs:
  build_tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npx token-transformer figamTokensToCss/input/design-token.json figamTokensToCss/input/base.json base
      - run: npx token-transformer figamTokensToCss/input/design-token.json figamTokensToCss/input/ves.json base,ves base --expandTypography=true
      - run: npx token-transformer figamTokensToCss/input/design-token.json figamTokensToCss/input/naruto.json base,naruto base --expandTypography=true
      - run: node figamTokensToCss/build.js
      - run: npx ts-node figamAssetsToComponents/generate.ts
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build tokens
  copy_tokens:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          src_branch: main
          src_path: figamTokensToCss/output/.
          dst_owner: JooelBks2000
          dst_repo_name: vite-vue-ts-storybook
          dst_branch: main
          dst_path: src/css/.
          username: JooelBks2000
          commit_message: copy css tokens
  copy_svg_components:
    runs-on: ubuntu-latest
    needs: [build_tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          src_branch: main
          src_path: figamAssetsToComponents/assets/components/.
          dst_owner: JooelBks2000
          dst_repo_name: vite-vue-ts-storybook
          dst_branch: main
          dst_path: src/components/Icon/.
          username: JooelBks2000
          commit_message: copy svg components
